### ISSUE TITLE
Error page not documented

### ISSUE THREAD

**Issue by juancs** [ndunand/moodle-mod_choicegroup#104]
Not quite important, but the page:

https://docs.moodle.org/31/en/error/choicegroup/pleasesetgroups

is not created. 

When a teacher creates a choicegroup and no group is created yet he/she is redirected to an error page where the "moreinfo" links to a page that doesn't exists.

**Comment by ndunand** [comment]
Hi,
Thanks for reporting this. I'll fix it in the next release.

**Comment by ndunand** [comment]
Fixed, pending new moodledocs wiki page moderation.
