### ISSUE TITLE
Wrong sorting when many groups autocreated

### ISSUE THREAD

**Issue by cdipe** [ndunand/moodle-mod_choicegroup#105]
Group choice have a problem when using auto created, two-digit number of courses sort order "Sort groups by Name" gets bad (pic 1 and 2) and "1" must be manually changed to "01", "2" to "02" and so on (pic 3).

![1](https://cloud.githubusercontent.com/assets/14754240/26240430/474b1e12-3c81-11e7-8ab1-88905616b4cc.png)

![2](https://cloud.githubusercontent.com/assets/14754240/26240432/4a9d3cb2-3c81-11e7-9dab-ba0fb7752fdd.png)

![3](https://cloud.githubusercontent.com/assets/14754240/26240446/5786c7a4-3c81-11e7-9891-be7d3c336dc4.png)

This problem isn't as big a problem, when auto creating group using letters instead of numbers; you get A-AZ, then B-BZ, then C-CZ and so on. (pic 4)

![4](https://cloud.githubusercontent.com/assets/14754240/26240452/5fa6d8c0-3c81-11e7-9325-6f1090a152e6.png)

I will also put this in Moodle tracker, since it looks the same when creating the groups so maybe that it's a moodle core problem to begin with. But since when it actually becomes a big issue is when using Group Choice, mayby you guys developing the plugin have a quicker solution.

**Comment by cdipe** [comment]
It was an old issue in Moodle tracker, I guess they don't prioritize this. But when using Group Choice it does become a problem. I added versions 3.0.8 and 3.2.3 that I know have the problem.
https://tracker.moodle.org/browse/MDL-22936

**Comment by ndunand** [comment]
I think it is a general problem when one is "sorting" numerical things alphabetically. Do you think it should be addressed in this plugin?

**Comment by cdipe** [comment]
Hi! The best would be if Moodle solved the general problem, but judging from the time the issue has spent in the tracker that doesn't seem likely. If there's a separate solution for Group Choice that would be appreciated.

**Comment by ndunand** [comment]
Hi,

I don't think I want to modify the plugin over this, especially since most other computer sorts behave identically.

**Comment by cdipe** [comment]
I can understand that. 
I'll link the tracker thread to this conversation, for the moodle developers to learn about issues caused by what might seem like a small problem when using only moodle core functionalities.
