### ISSUE TITLE
Remove the condition to create at least two groups

### ISSUE THREAD

**Issue by JorgenIvarsson** [ndunand/moodle-mod_choicegroup#106]
We at Umeå university would like the possibility to create one group. When we try to do that we get a error message saying we have to create at least two groups. Choices don't have this requirement. I don't see any reason to impose this rule when it comes to using this plugin. It should be possible to let student assign them self (or not) to a group without there being a second group choice.

**Comment by miroi** [comment]
Him

I agree with this idea. To overcome the one group problem, I had to create an auxiliary group.

But much better is having the groupchoice working also  for one group.

**Comment by ndunand** [comment]
I agree. This has been fixed by https://github.com/ndunand/moodle-mod_choicegroup/commit/68383c4c091e3d432ab6fd6ac0045fea7f85492e

**Comment by JorgenIvarsson** [comment]
Thanks Nicolas!
