### ISSUE TITLE
Add heading title and update notifications/button

### ISSUE THREAD

**Issue by adpe** [ndunand/moodle-mod_choicegroup#107]
Hello @ndunand 

I wanna ask if you can merge my changes (will follow) into the official repo. In general, I think this plugin must be rewrited, because in Moodle 3.3 there are some YUI-JS errors on the developer console. The AMD procedure should be chosen here. So the plugin it's actual broken in Moodle 3.3.

It would be also nice, if the response view would like the mod_choice's one:
![image](https://user-images.githubusercontent.com/9467708/34948928-d7fb0634-fa0e-11e7-9531-4c65d94649a9.png)

And not like this:
![image](https://user-images.githubusercontent.com/9467708/34948977-f9ad7078-fa0e-11e7-9071-71c9f225ed70.png)

I'll looking with our organization, if we can help you improve this plugin.
Adrian

**Comment by ndunand** [comment]
Hi @adpe I'd be glad to merge any improvements. The plugin indeed still uses the old YUI api and as you said should be rewritten as an AMD module. I don't think it is "broken" because still performs well in Moodle 3.3 but if you're more specific about errors thrown I'll correct these.

**Comment by ndunand** [comment]
Thanks @adpe . I've merged #109 – have you made any other improvements you wish to share?

**Comment by adpe** [comment]
Hello @ndunand 

Thanks for the integration. I think atm it's fine.

Kind regards
Adrian

=> Closing the issue
