### ISSUE TITLE
YUI JavaScript errors on responses page

### ISSUE THREAD

**Issue by adpe** [ndunand/moodle-mod_choicegroup#108]
Hello @ndunand 

Here are the mentioned javascript errors. I'm testing on Moodle 3.3.3+ and have the newest release of the plugin in use.

![image](https://user-images.githubusercontent.com/9467708/34976881-c7ac4d30-fa98-11e7-926b-6e2c7bfb4a15.png)

They appear after clicking the Select or Deselect all link. As result, the functionality of this two links are not working.

Kind Regards
Adrian

**Comment by adpe** [comment]
Hello @ndunand 
Can you reproduce the problem?

**Comment by s-cenni** [comment]
Hi Adrian,
I have the same problem. We are using 3.3.4 and I’ve update the plugin but I still get the same error.
I think that the problem is similar to this bug: https://tracker.moodle.org/browse/MDL-60546

**Comment by s-cenni** [comment]
Hi @ndunand,
I created a pull request to fix this error.
Bye
Sara

**Comment by s-cenni** [comment]
I changed the code following @adpe  and @ndunand suggestions.

**Comment by Kathrin84** [comment]
This is also / still an issue on Moodle 3.4.1+ (just for the sake of completeness).

**Comment by MelvRom** [comment]
Hi,

Can confirm that this is a problem in our Moodle 3.3. installation.
