### ISSUE TITLE
Call to print_error (L71 mod_form.php) generates a link to a non-existing documentation page

### ISSUE THREAD

**Issue by jrm-unamur** [ndunand/moodle-mod_choicegroup#110]
Documentation doesn't exits for mod_choicegroup in official moodle docs. It's not a serious issue, but, anyway...
Regards
![capture d ecran 2018-02-13 a 10 20 28](https://user-images.githubusercontent.com/4832513/36142939-db088016-10a9-11e8-8b47-5bac6f43dcb0.png)

**Comment by ndunand** [comment]
Fixed, pending new moodledocs wiki page moderation.
