### ISSUE TITLE
Does not support the Privacy API

### ISSUE THREAD

**Issue by thepurpleblob** [ndunand/moodle-mod_choicegroup#113]
Could support be added for the new Privacy API? Although there is a 3.5 version of the plugin it is currently not compliant with this new API.

**Comment by ndunand** [comment]
Yes but support would be very limited as this plugin does not record user choices. Likely, a `\core_privacy\local\metadata\null_provider` will be implemented.

**Comment by ndunand** [comment]
(the user choices are recorded by the core_group Moodle component)

**Comment by ndunand** [comment]
Fixed by d9602ba
