### ISSUE TITLE
Choice Group: clicking 'Save my choice' button show last selection

### ISSUE THREAD

**Issue by StudiUM-S** [ndunand/moodle-mod_choicegroup#119]
Hello,

I am not sure if I am the first to have the bug, but I wanted to tell you about it.

Creating a module: Choice Group in Moodle.

Number of groups: 2+

Settings:
[x] Allow enrollment to multiple groups

Publish results
- Always show results to students

Privacy of results
- Publish full results, showing names and their choices

Allow choice to be updated
- Yes

Show column for unanswered
- Yes

Limit the number of responses allowed
- Enable

General limitation
- 5 (any number)

------------------------------------

When creating a choice group module with the previous settings, the "Save my choice" doesn't really show the real choice.
Check group 1 and "Save my choice"

Check group 2 while keeping group 1 and "Save my choice"

The text is "Your selection is g1" while it showed the correct members with capacity.

In the end, it remembers the previous selection but it did really save the selection in the database. It was tested on Chrome & Safari on Mac OSX with the same results.

Screenshot:
![capture d ecran 2018-07-05 a 09 15 50](https://user-images.githubusercontent.com/40863265/42343118-09fec566-8066-11e8-9ecc-e287dbd30754.png)

**Comment by ndunand** [comment]
Thanks for reporting this @StudiUM-S , this has been fixed in e242b32.
