### ISSUE TITLE
Fatal error: Uncaught moodle_exception: No groups defined in course.

### ISSUE THREAD

**Issue by sleitao** [ndunand/moodle-mod_choicegroup#120]
Using the latest version 2018070900 for moodle 3.5, if the course doesn't have groups we get an error when trying to create the activity:
"Fatal error: Uncaught moodle_exception: No groups defined in course. "
With debugging off users get a blank page. 
Is it working as designed?

Than you!

**Comment by ndunand** [comment]
No, this is not working as designed. Below is what you should see.
<img width="833" alt="screenshot 2018-10-29 at 09 29 32" src="https://user-images.githubusercontent.com/762972/47637874-52a84100-db5d-11e8-9fa0-349aac7e2e4a.png">
Can you double check your plugin version number?

**Comment by sleitao** [comment]
I was able to understand that the problem reported has its origin on another plugin. A moodle filter that is not handling exceptions properly. Choice Group module is working as expected so I am going to close this issue. Thank you for your input and I apologize for the inconvenience.

**Comment by ndunand** [comment]
Hi and thanks for taking the time to report back.
