### ISSUE TITLE
Cannot cancel activity creation unless a group is selected

### ISSUE THREAD

**Issue by t-schroeder** [ndunand/moodle-mod_choicegroup#124]
Reproduce:
1. go to the choicegroup activity creation form
2. without entering anything click cancel
=> alert pops up: "please select at least one group to choose from"

Expected behavior:
I should be able to cancel the activity creation without selecting a group.

**Comment by ndunand** [comment]
Thanks you are right indeed this is not the expected behaviour. This will be corrected in the next release.

**Comment by abias** [comment]
Hi @ndunand ,

may I ask you about the status of this minor issue? It has not been fixed in the "next release" as you wrote above ;)

Thanks in advance,
Alex

**Comment by ndunand** [comment]
Fixed by 8aafb1583bbb43c0ba sorry for the delay

**Comment by abias** [comment]
Thank you, Nicolas!
