### ISSUE TITLE
Group choice index page does not display multiple answers

### ISSUE THREAD

**Issue by amandadoughty** [ndunand/moodle-mod_choicegroup#127]
mod/choicegroup/index.php only shows one answer per activity. This is confusing if the users has selected multiple answers.

Patch attached.
[CMDLTWO-1623.txt](https://github.com/ndunand/moodle-mod_choicegroup/files/3450711/CMDLTWO-1623.txt)

**Comment by ndunand** [comment]
Hi @amandadoughty , this is now fixed by 8c74d57
