### ISSUE TITLE
Group sign-up form not visible

### ISSUE THREAD

**Issue by upats** [ndunand/moodle-mod_choicegroup#132]
Hi, I'm seeing a weird issue with this plugin. I hope i'm not missing something obvious. I'm currently evaluating it on a test server running Moodle 3.6.7+ and choice group v 2019051001.

When a Group Choice activity is added in Moodle, the sign-up form does not appear on the activity page. (screenshot 1)
![2019-12-11_12-00-54](https://user-images.githubusercontent.com/7084108/70658851-b1baff00-1c13-11ea-8eaf-84bec002c2b5.png)

Inspecting the element reveals that the CSS for the .tableform class is set to hidden, and also fixed at 70px width. (screenshot 2)
![2019-12-11_12-00-49](https://user-images.githubusercontent.com/7084108/70658909-d1eabe00-1c13-11ea-947e-aac46e44d991.png)

Unchecking those two properties allows the form to display fine. (screenshot 3)
![2019-12-11_12-01-11](https://user-images.githubusercontent.com/7084108/70658938-e29b3400-1c13-11ea-81df-bba1c5eceabf.png)

I haven't been able to test out on a vanilla install, but I looked through and deleted my SCSS and tried different themes to see if I could find a conflict with no luck.

**Comment by ndunand** [comment]
Hi and thanks for reporting this.

The CSS selector and rules you are referring to do not belong to the Group Choice module, though. Most likely, it comes from the theme used or another specific configuration.

Could you check and see whether the activity displays correctly with a standard theme like Boost or Classic ?

**Comment by upats** [comment]
Thanks, I'm using Boost and also tried Clean on 3.6, same effect...I wonder if it might be a conflict with another plugin. No worries for me as this is just a test server. If I ever do identify the conflict/setting that is doing this I will post back here.

**Comment by ndunand** [comment]
Alright, thanks for reporting back. This is indeed the most likely due to another plugin you have, one that does not prefix its CSS rules correctly.
