### ISSUE TITLE
MOODLE_INTERNAL checking and Moodle code style rules

### ISSUE THREAD

**Issue by OlenaTatarintseva** [ndunand/moodle-mod_choicegroup#136]
Hello,

First of all I want say thank you for your work with the plugin.

I just would like to suggest, that it would be good to add MOODLE_INTERNAL check in php files in the plugin to comply  Moodle code requirements: https://docs.moodle.org/dev/Coding_style#Require_.2F_include.
There are some files in db and backup directory, where MOODLE_INTERNAL check is missed.

Best regards,
Olena Tatarintseva

**Comment by ndunand** [comment]
Hello,

Thanks for reporting this, you are absolutely right. I'll try and fix this for the next release.

**Comment by ndunand** [comment]
Fixed
