### ISSUE TITLE
mod_groupchoice makes backups impossible to restore

### ISSUE THREAD

**Issue by Richardvi** [ndunand/moodle-mod_choicegroup#138]
We have some deleted courses that needed to be restored. In these courses there were references to mod_choicegroup. This made it that we could not restore the backups, they fail every time. See picture.

This will force us away from this plugin as we are now in danger of not being able to restore courses when needed.

![image](https://user-images.githubusercontent.com/5486910/85920376-698fc100-b873-11ea-8813-e732a4f7e191.png)

Hope this can be fixed. Using Moodle 3.7 and latest mod_choicegroup posted in the plugin directory.

**Comment by ndunand** [comment]
Hi, and thanks for reporting this.

Could you please paste the whole part of the error log concerning this issue as text? The image is difficult to search. We'll then look at this asap.
 
Thanks!

**Comment by KomodoDeveloper** [comment]
Hello, I tried to reproduce Richardvi's issue. I created a course with choicegroup activities, I made a backup and I deleted the course. I didn't get an error when restoring the course. The restoration was a sucess. Try on Moodle version 3.9

**Comment by Richardvi** [comment]
I'm sorry, I don not have the full logs. Just this screenshot. As stated in the first post, we use Moodle 3.7. Perhaps this has been solved in Moodle 3.9.

**Comment by ndunand** [comment]
@Richardvi thanks for your feedback. Could you also have someone on your side try to reproduce this in the Moodle interface? From your screenshot we can see you're using Moosh – which we have no experience with – but testing your issue within Moodle itself yielded no errors.

**Comment by Richardvi** [comment]
@ndunand the problem is that even with debugging on, we dit not get any error except _'restore failed - contact administrator'._ That's why we used Moosh to get at least some more info on what went wrong.

This was a course backup of 6.8 GB, so rather big. I wish I could share the backup but it contains to much personal information of Moodle users.
