### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kraebsli** [ndunand/moodle-mod_choicegroup#142]
Hi there,
we got a request for an option to choose only a certain number of groups if multiple selection of groups is allowed.

Regards Kathrin

**Comment by kraebsli** [comment]
Hi @ndunand 
yes, exactly that is the setting required; in this case out of 10 groups only 2 should be selected.

**Comment by ndunand** [comment]
Alright, understood. No available time for dev in the ear future, so if you have someone to work on this I'd gladly review and integrate.

**Comment by kraebsli** [comment]
ok, I will see if I have possibilities.

**Comment by jonathanjoegit** [comment]
Hello @kraebsli & @ndunand,

A colleague asked me the same enhancement. To be able to limit the number of groups a student can enroll in (2, 3, 4, ...). 

Do you have some news about this topic ?

Thank you :)
