### ISSUE TITLE
Can't install mod_choicegroup on course page.

### ISSUE THREAD

**Issue by orlov-bug44** [ndunand/moodle-mod_choicegroup#143]
Hi!

It always shows an exclamation mark in the name field.

[2020-11-26 09-33-41.zip](https://github.com/ndunand/moodle-mod_choicegroup/files/5601026/2020-11-26.09-33-41.zip)

**Comment by orlov-bug44** [comment]
[2020-11-26 09-33-41.zip](https://github.com/ndunand/moodle-mod_choicegroup/files/5601021/2020-11-26.09-33-41.zip)

**Comment by canatojr** [comment]
Hello!

Same here, using moodle 3.10+ (Build: 20201113).

In the same way reported by Kazi Chawky (https://moodle.org/plugins/mod_choicegroup), the problem started just after upgrading to moodle 3.10 and in my case that problem is happening in both boost and classic theme.
  
Best regards!
Osvaldo

**Comment by ndunand** [comment]
The exclamation mark in the name field is normal, it just indicates a mandatory field: as in most (all?) Moodle activities, the name is required.

**Comment by canatojr** [comment]
Sorry for not being so clear!

So, let me copy the message posted by Kazi Chawky in moodle plugin page:

"I can no longer instantiate a group choice activity in 3.10+. When I save the settings, nothing happens and I stay on the settings page".

As I could see by the movie posted by orlov-bug44, what he was reporting is exactly this: we can't more save the activity.

**Comment by ndunand** [comment]
Thanks for the clarification. I actually checked the MKV file Kazi posted above, but could not replicate the issue on a vanilly Moodle 3.10 with only this extra plugin installed.

When the settings page reloads like that, is usually means there should be a red error message somewhere, indicating what went wrong. Is there no such mention?

**Comment by orlov-bug44** [comment]
How debug?

**Comment by canatojr** [comment]
Hi Nicolas!

Unfortunately, no error message is displayed even when I enter in debbuging mode with developer messages enabled.

**Comment by orlov-bug44** [comment]
So, how are we going to fix it?

**Comment by ndunand** [comment]
Hello @orlov-bug44 

How did you come to this conclusion ? Did you get any error message that could help in fixing the plugin?

**Comment by orlov-bug44** [comment]
On a clean installation, I began to consistently enable all the options in the settings that are in prod, and when I turned on the "globalsearch", the module broke, and when I turned it off, it started working again.
No error message.
Maybe module has broke HTML/CSS code...

**Comment by merrill-oakland** [comment]
We are seeing thing too. I will take a look at it tonight and hopefully get a patch ready.

**Comment by merrill-oakland** [comment]
I have submitted a patch in pull request #144. This issue was specific to global search being enabled in 3.10. The new global search bar uses a mform, which was confusing the YUI javascript.

**Comment by ndunand** [comment]
Thans @merrill-oakland for looking into this and providing a patch.

**Comment by ndunand** [comment]
Releasing new version including @merrill-oakland 's patch now.
