### ISSUE TITLE
Group Choice Activity cannopt be instantiated in Moodle 3.10

### ISSUE THREAD

**Issue by frankkoch** [ndunand/moodle-mod_choicegroup#145]
Hi Nicolas,
Unfortunately, a Group Choice Activity cannot be instantiated in Moodle 3.10 anymore. 
When settings are saved, you remain on the settings page without an error being indicated.
Best, Frank

**Comment by ndunand** [comment]
Hi Frank,

Sorry for the delay. My testing showed that all worked as expected. Could you please provide more information:

 - exact Moodle version
 - exact plugin version
 - course setup and whether groups were already created beforehand?
 - do you have global search enabled (could this be related to #143) ?

**Comment by ndunand** [comment]
@frankkoch could not reproduce ... just tested using

 - Moodle 3.10.1+ (Build: 20210204)
 - mod_choicegroup 1.21 for Moodle 3.5-3.10 (Build: 2020121900)

works without issues.

Feel free to reopen with more information.
