### ISSUE TITLE
Adjust column size in group window

### ISSUE THREAD

**Issue by taraghi** [ndunand/moodle-mod_choicegroup#146]
In the activity settings, the first cell in the table ist very wide, but the select field is not wide enough. See bellow!

This is a bit inconvenient, because you can't see the whole group name.

![Bildschirmfoto 2021-01-27 um 16 58 33](https://user-images.githubusercontent.com/204101/106017691-01cb7e00-60c1-11eb-9c76-400a0351da58.png)

**Comment by ndunand** [comment]
Thanks! I'll look into it ... if you hover with the mouse cursor over one group, does it show the whole group name ?

**Comment by taraghi** [comment]
No it doesn't.

**Comment by ndunand** [comment]
Hi, this is now fixed by 718eeb7
