### ISSUE TITLE
"Allow enrollment to multiple groups" setting always unchecked when restoring/duplicating course

### ISSUE THREAD

**Issue by izendegi** [ndunand/moodle-mod_choicegroup#148]
Hi,

We've detected that when duplicating (or backup&restoring) a course with a group choice activity on it, the group choice activity of the new course always has the "Allow enrollment to multiple groups" setting unchecked; it seems like it goes to the default value (unchecked) instead of using the original value (checked).

We are using the latest version of the plugin (1.21 for Moodle 3.5-3.10) on a Moodle 3.10 site (it happens with 3.10.1 and 3.10.2)

**Comment by ndunand** [comment]
Thanks @izendegi for reporting this, will be fixed for next release (hopefully by June).

**Comment by ndunand** [comment]
Note: could be because `'multipleenrollmentspossible'` is missing in https://github.com/ndunand/moodle-mod_choicegroup/blob/master/backup/moodle2/backup_choicegroup_stepslib.php#L40

**Comment by izendegi** [comment]
Yes, we've tested that fix and works like a charm, thank you @ndunand

**Comment by ndunand** [comment]
Thanks for your feedback!
