### ISSUE TITLE
Activity Completion not working

### ISSUE THREAD

**Issue by tbeachy** [ndunand/moodle-mod_choicegroup#155]
I just updated to the latest version of this plugin (1.32), and now Choice Group activity is not being completed.

```
Debug info: Module choicegroup claims to support
FEATURE_COMPLETION_HAS_RULES but does not have required
choicegroup_get_completion_state function
Error code: err_system
×Stack trace:
line 1378 of /lib/completionlib.php: moodle_exception thrown
line 700 of /lib/completionlib.php: call to completion_info->internal_systemerror()
line 623 of /lib/completionlib.php: call to completion_info->internal_get_state()
line 749 of /lib/completionlib.php: call to completion_info->update_state()
line 98 of /mod/choicegroup/view.php: call to completion_info->set_module_viewed()
```

Thanks for any help!

**Comment by ndunand** [comment]
Hi @tbeachy , which Moodle version are you using?

**Comment by grabs** [comment]
Hi, same here on Moodle 3.9.
The function `choicegroup_get_completion_state()` is missing but required because of the feature `FEATURE_COMPLETION_HAS_RULES`.
Thanks for this really good plugin!

**Comment by katjaclempinen** [comment]
We have same problem! 
Plugin is really good, but not working just now. Moodle 3.9.9+ Same error message

**Comment by tbeachy** [comment]
Thank you for fixing!  I will not be able to test and provide feedback right away as I have downgraded to the previous version in the meantime due to a project deadline.  If anyone else is able to test in the meantime and confirm, that would be very helpful.
Thanks again!

**Comment by ndunand** [comment]
The newly released version now available on Moodle.org includes the fix.

**Comment by katjaclempinen** [comment]
Thank you for the fix. I'll try the fix first in the morning!

> The newly released version now available on Moodle.org includes the fix.

**Comment by katjaclempinen** [comment]
> Thank you for the fix. I'll try the fix first in the morning!
> 
> > The newly released version now available on Moodle.org includes the fix.

The new version works in our Moodle. Thank you so much!

**Comment by ndunand** [comment]
Thanks for reporting back here!
