### ISSUE TITLE
Group Choice restore from Recycle Bin loses group settings

### ISSUE THREAD

**Issue by ebithell** [ndunand/moodle-mod_choicegroup#163]
Seen in Moodle 3.5.18 (mod_groupchoice version 1.15), 3.9.11 (version 1.33) and 3.11.6 (version 1.33).

When a Group Choice activity is restored from the Course Recycle Bin, the allocated Groups for the activity are not restored.

Steps to reproduce:
1. Create a group within a course (Group A)
2. Add a Group Choice activity
3. Select Group A from the activity's available groups and add it to the selected groups
4. Save the activity
5. Delete the Group Choice activity; wait for the cron to run and the activity to appear in the Recycle Bin
6. Restore the activity from the Recycle Bin

Expected result:
- The same general behaviour as for delete/restore of other activities i.e. all activity settings are restored
- Group A is the selected group for the restored activity

Actual result:
- With developer debugging and error reporting enabled, a PHP notice & warning are shown:
Notice: Undefined property: stdClass::$option in /var/www/moodle/mod/choicegroup/mod_form.php on line 218
Warning: Invalid argument supplied for foreach() in /var/www/moodle/mod/choicegroup/mod_form.php on line 218 
- A record for a group with groupid = 0 exists mdl_choicegroup_options
- Selecting a group and saving the activity clears this database record and replaces it with a new and correct entry

Course backup & restore operate as expected but activity duplication also loses its groups setting, with the same PHP messages.

(description of cause and proposed solution with patch following in comments)

**Comment by ndunand** [comment]
Thanks @ebithell for spotting this, working it out and sharing your fix.

I completely agree with your logic and quickly tested your patch, which I have just integrated. This will be released along with the upcoming version officially supporting Moodle 4.0.

**Comment by jumabgz** [comment]
Hello Nicolas,

it seems that this problem is back. I am testing with moodle 3.9.18 + mod_choicegroup 1.38 (2022092202) and after restoring a course with mod_choicegroup with group selection set, the restored course shows the activity without the group selection of the original course (groups are being restored correctly at course level).

The same is true in 1.37. Before we were using 1.33 with moodle 3.9.15 and it was fine.

I hope you can check it out.

Regards

**Comment by jumabgz** [comment]
Hello, I have continued testing and I see that in the restored course, even though the selected groups field, in the activity settings, is empty, the student still sees as eligible the original groups and only the original ones and they can still make the selection. If the course had more groups not included in the original activity, they are not shown eligible in the restored activity. This is fine, however, in the settings, the selected groups field becomes empty and could be a problem or be confusing for the teacher.

This behavior occurs both in choicegroup 1.38 with moodle 3.9.18 and moodle 3.11.11.

Regards
