### ISSUE TITLE
Define a FEATURE_MOD_PURPOSE and new icon for Moodle 4

### ISSUE THREAD

**Issue by juancs** [ndunand/moodle-mod_choicegroup#165]
Well, don't know if this is the way to ask for this kind of things.

The plugin seems to work on Moodle 4, but its icon doesn't follow the new boost guidelines. 

To fix this, a new icon should be added and FEATURE_MOD_PURPOSE must be added to choicegroup_supports() returnin MOD_FEATURE_OTHER (I tihnk this is the one to choose).

I can provide a patch for the second one, but not for the first :) 

Are you planning to change this? :)

Thanks in advance.

**Comment by lucaboesch** [comment]
Maybe something like this, @juancs 
![monologo](https://user-images.githubusercontent.com/377279/172232521-4e24f896-aee6-420e-95da-336ae76c4fd7.svg)

**Comment by ndunand** [comment]
Thanks @lucaboesch for the icon 😊 I've now just merged this in #166
