### ISSUE TITLE
FEATURE_MOD_PURPOSE and MOODLE 3.x

### ISSUE THREAD

**Issue by voegii** [ndunand/moodle-mod_choicegroup#172]
Hi Nicolas

As you introduced the usage of FEATURE_MOD_PURPOSE constant in version 2022090500, this version is no longer compatible to Moodle 3.x? See https://moodledev.io/docs/devupdate#activity-icons.

As a workaround and because other plugins also do it this way, we temporary defined the FEATURE_MOD_PURPOSE and MOD_PURPOSE_* constants in config.php (Moodle 3.11).

Best regards
Sascha - FFHS

**Comment by ndunand** [comment]
Hi Sasga @voegii ,

Indeed sorry this was an unintended side effect. Commit ae003d806e28210 fixes this, to be released now-ish.

**Comment by bdpz** [comment]
Hi,
I wrote this this morning to resolve the problem  (but I see that a bugfix was published) :

function choicegroup_supports($feature) {
    switch($feature) {
        case FEATURE_GROUPS:                  return true;
        case FEATURE_GROUPINGS:               return true;
        case FEATURE_GROUPMEMBERSONLY:        return true;
        case FEATURE_MOD_INTRO:               return true;
        case FEATURE_COMPLETION_TRACKS_VIEWS: return true;
        case FEATURE_COMPLETION_HAS_RULES:    return true;
        case FEATURE_GRADE_HAS_GRADE:         return false;
        case FEATURE_GRADE_OUTCOMES:          return false;
        case FEATURE_BACKUP_MOODLE2:          return true;
        case FEATURE_SHOW_DESCRIPTION:        return true;

        default :
            if (defined('FEATURE_MOD_PURPOSE')) {
                return MOD_PURPOSE_OTHER;
            }
            return null;
    }
}

Best
Baptiste

**Comment by ndunand** [comment]
Hi @bdpz ,

Thanks for your solution, but this wouldn't be future-proof if e.g. Moodle 5.x would bring a new feature called `FEATURE_NEWFEATURE` ... then your code would rwturn `MOD_PURPOSE_OTHER`.

Anyway, let me know if my hack appears satisfactory to you or not.

Kind regards,
Nicolas

**Comment by bdpz** [comment]
Thanks @ndunand 
I will try it more conscientiously in a test environment this time ;)
That was a quick fix that I have found in other modules. PHP 8 is a little more strict with undefined constants.

**Comment by bdpz** [comment]
@ndunand 
All is ok for me with the new version on Moodle 4 + PHP 8 and Moodle 3.11 + PHP 8
Thanks for your quick bugfix !

**Comment by ndunand** [comment]
@bdpz thanks for reporting back!
