### ISSUE TITLE
Form submit button instead of input

### ISSUE THREAD

**Issue by Kemmotar83** [ndunand/moodle-mod_choicegroup#174]
Hi,

upon other important (but heavy) requests about upgrading to templates, ecc... (), could please fix a minor "issue"?

In the view form the "Save my choice" submit should be changed from input type="submit" to button type="submit". This will let screenreader better read the page.

renderer.php - row 174
```
$html .= html_writer::tag('button', get_string('savemychoicegroup','choicegroup'), array(
    'type'=>'submit',
    'class'=>'btn btn-primary',
    'style' => $initiallyHideSubmitButton?'display: none':''
));

```
Thanks,
Giorgio

**Comment by NicoAlexH** [comment]
Fixed by https://github.com/ndunand/moodle-mod_choicegroup/pull/204, it will be available in the next release :)
