### ISSUE TITLE
Possible to choose a group even if the date has passed

### ISSUE THREAD

**Issue by agarnav** [ndunand/moodle-mod_choicegroup#175]
Hello, 
A student can open the code inspector of his browser. It modifies the properties of the radio buttons and can submit the form. He is then registered in the group. See screenshots.
![image](https://user-images.githubusercontent.com/2854441/198319458-30ace98c-68e3-421d-91c8-72d58b064c3c.png)
![image](https://user-images.githubusercontent.com/2854441/198319531-a796ba9c-f64b-4b62-b261-670c8a2aa5d6.png)
![submit](https://user-images.githubusercontent.com/2854441/198319828-7adf6ab3-7473-43e3-bcdc-9a87448b53e3.png)
Thanks for watching

**Comment by ndunand** [comment]
Thanks for reporting; this is indeed something I overlooked in the way data is processed. We'll have a look into this asap.

**Comment by NicoAlexH** [comment]
Fixed by [a63b966](https://github.com/ndunand/moodle-mod_choicegroup/commit/a63b96648dabd02d0bede9979a20bce79098f6b0)

Thanks for reporting !
