### ISSUE TITLE
Choicegroup 1.38 uninstall on Moodle 3.11.11 leads to core_plugin/err_unknown_plugin

### ISSUE THREAD

**Issue by jumabgz** [ndunand/moodle-mod_choicegroup#180]
Hello, 

testing locally, when uninstalling the choicegroup plugin (version 1.38, moodle 3.11.11), I have detected that it leads to _core_plugin/err_unknown_plugin_ error. This error is displayed after uninstalling and updating the moodle DB. It is shown in the browser, when accessing the administration area.

Here the detail of the error:

```
core_plugin/err_unknown_plugin.

Debug info:
Error code: err_unknown_plugin
$a contents: Array
(
[plugin] => mod_choicegroup
)
Stack trace:
line 583 of /lib/classes/plugin_manager.php: moodle_exception thrown
line 436 of /admin/tool/mobile/classes/api.php: call to core_plugin_manager->plugin_name()
line 184 of /admin/tool/mobile/settings.php: call to tool_mobile_api::get_features_list()
line 81 of /lib/classes/plugininfo/tool.php: call to include()
line 682 of /admin/settings/plugins.php: call to core\plugininfo/tool->load_settings()
line 8859 of /lib/adminlib.php: call to require()
line 8746 of /lib/adminlib.php: call to admin_get_root()
line 202 of /admin/plugins.php: call to admin_externalpage_setup()
```

The moodle cache purge does not solve the problem and having uninstalled the plugin, you can see that in DB, in tables such as roles or capabilities, there are traces of the plugin. I don't know if it has to do with it.

For the moment what I have done, to be able to access again to the moodle administration has been to reinstall choicegroup. However, the activity does not work. The checkbox that the user must use to select a group is grayed out (disabled). It seems that something is corrupted at role or capabilities level.

Does it happen to anyone else? I report it in case you can replicate it and find a solution.

Thank you,
Regards

**Comment by ndunand** [comment]
Hi @jumabgz ,
Thanks for reporting this. This is quite a big issue indeed. When you mention

>  in DB, in tables such as roles or capabilities, there are traces of the plugin

Could you be more specific?

**Comment by NicoAlexH** [comment]
Hello @jumabgz, 

I have been investigating this issue today (sorry for the delay!), and I haven't been able to reproduce it with Choicegroup 1.44 on Moodle 4.3.2. I get no error from uninstalling the plugin and no disabled checkboxes on reinstall. It does keep traces of the plugin in the database, but I guess that is the expected behavior.
Do you still encounter those issues with recent versions of the plugin or can we consider it as solved ?

**Comment by jumabgz** [comment]
Hi @NicoAlexH ,

I'm sorry I couldn't test it when you posted your last message. Now I'm working with Moodle 4.1. I tested it in this version (_Moodle 4.1.9+ (Build: 20240313) (2022112809.06) and Choicegroup 1.42.1 for Moodle 3.11-4.2 (Build: 2023110900)_) and it works well. Thank you for your time.

Regards

**Comment by NicoAlexH** [comment]
Hi @jumabgz, no problem, good news then ! Let us know if you face the issue again in the future :) 

Cheers
