### ISSUE TITLE
Selected groups still show under Available groups in settings

### ISSUE THREAD

**Issue by cdipe** [ndunand/moodle-mod_choicegroup#188]
- When adding groups in Group Choice settings, from _Available Groups_ to _Selected groups_, they still remain in the Available groups menu. 

- The expected behaviour would be that when added to _Selected groups_, they disappear from _Available groups_. And, if removed from _Selected groups_, they should show under _Available groups_ again.

Moodle 4.1.1 (Build: 20230116), Group Choice 1.39 for Moodle 3.9-4.1 (Build: 2023010300)

**Comment by NicoAlexH** [comment]
Hi Peter, 

Oh I see now, thanks for clarifying ! You're right, the expected behaviour you describe would make more sense. I'll look into it :) 

Have a nice day, 
Nicolas

**Comment by NicoAlexH** [comment]
Fixed by https://github.com/ndunand/moodle-mod_choicegroup/pull/203, it will be available in the next release :)
