### ISSUE TITLE
Update on empty existing groupchoice options

### ISSUE THREAD

**Issue by voegii** [ndunand/moodle-mod_choicegroup#189]
When 
- we have no groupchoice options (this can happen on a restore or an import), 
- and we go to groupchoice settings
- and we add some groups
- and we want to save
we receive this error message: "Could not update choicegroup".

![image](https://user-images.githubusercontent.com/40361859/222206530-5424e7f5-2f55-4486-9f62-9f17b8293740.png)

**Comment by lucaboesch** [comment]
@ndunand A lecturer encountered this as well on our place, we do try the fix https://github.com/ndunand/moodle-mod_choicegroup/pull/190 and then we'll report back.

**Comment by ndunand** [comment]
Thanks @lucaboesch you input will be valued. We just don't want to induce any regressions but we'll take the time to review this in the near future.

**Comment by lucaboesch** [comment]
Dear @ndunand I can confirm the fix works. Of course, and I know that you are aware of this, I can not stress enough on how much Behat tests do help for regression prevention.

**Comment by NicoAlexH** [comment]
Fixed by merging https://github.com/ndunand/moodle-mod_choicegroup/pull/190
