### ISSUE TITLE
ISSUE:  timing configuration on Moodle 4.1

### ISSUE THREAD

**Issue by gberrueco-URJC** [ndunand/moodle-mod_choicegroup#193]
Hey, we've found a bug in the timing configuration. The plugin allows the closing date to be earlier than the opening date. This setting doesn't show any error or warning while setting up the group selection.

Can anything be done about it?

Thanks a lot.

**Comment by ndunand** [comment]
Hello,
Thanks for reporting this. We can confirm and reproduce the wrong behaviour, and will fix it.

**Comment by NicoAlexH** [comment]
Hi, this bug should now be fixed : https://github.com/ndunand/moodle-mod_choicegroup/commit/ef08477da1014df7471949057d1ec64e1152791f 

Thanks for reporting it !
