### ISSUE TITLE
Could not update choicegroup, Error code: cannotupdatemod

### ISSUE THREAD

**Issue by Richardvi** [ndunand/moodle-mod_choicegroup#197]
When selecting groups in the group choice module and pressing 'save' this is the error we get (with full debugging on)

Unfortunately, I don't have any other information... the debugging shows very little info.

Could not update choicegroup

[More information about this error](http://docs.moodle.org/402/en/error/moodle/cannotupdatemod)

Debug info:
Error code: cannotupdatemod×Dismiss this notification
Stack trace:
line 660 of /course/modlib.php: moodle_exception thrown
line 173 of /course/modedit.php: call to update_moduleinfo()

![image](https://github.com/ndunand/moodle-mod_choicegroup/assets/5486910/b700f8df-d6a5-4b36-9352-da42451a335b)

**Comment by Richardvi** [comment]
Found more info in the error-log:

[05-Sep-2023 13:59:34 Europe/Amsterdam] PHP Warning:  Undefined property: stdClass::$option in /home/learn/public_html/mod/choicegroup/mod_form.php on line 218
[05-Sep-2023 13:59:34 Europe/Amsterdam] PHP Warning:  foreach() argument must be of type array|object, null given in /home/learn/public_html/mod/choicegroup/mod_form.php on line 218
[05-Sep-2023 13:59:34 Europe/Amsterdam] PHP Warning:  Attempt to read property "uservisible" on null in /home/learn/public_html/course/format/tabs/lib.php on line 94
[05-Sep-2023 13:59:34 Europe/Amsterdam] Default exception handler: Could not update choicegroup Debug: 
Error code: cannotupdatemod
* line 660 of /course/modlib.php: moodle_exception thrown
* line 173 of /course/modedit.php: call to update_moduleinfo()

**Comment by ndunand** [comment]
Hi,
Thanks for reporting . Could you get us the following extra information?
 - Moodle version 
 - mod_choicegroup version

**Comment by Richardvi** [comment]
Yes, sorry. Moodle 4.2.2, PHP 8.0, choicegroup 1.41 for Moodle 3.9-4.2 (Build: 2023061400)

**Comment by Richardvi** [comment]
It could be a duplicate of https://github.com/ndunand/moodle-mod_choicegroup/issues/189

**Comment by pmatabiau** [comment]
Hi,
here too. (Moodle 4.1.4+, mod_choicegroup version 2023061400).
[voegii fix](https://github.com/ndunand/moodle-mod_choicegroup/pull/190) works fine (since Mars 1). Please accept the pull requests and publish a new version.

**Comment by Richardvi** [comment]
Any progress on this? Some of my teachers are getting annoyed by this bug. Publishing a new version like @pmatabiau says would help us as well!
