### ISSUE TITLE
Moodle 4.3 final deprecation of *_get_completion_state() callbacks

### ISSUE THREAD

**Issue by marcestone** [ndunand/moodle-mod_choicegroup#206]
Hi!
I found that in https://github.com/ndunand/moodle-mod_choicegroup/blob/master/lib.php#L1086, the `choicegroup_get_completion_state` function is still declared in the latest version. According to the Moodle Tracker ticket https://tracker.moodle.org/browse/MDL-71196, the *_get_completion_state() callbacks were deprecated and are being replaced by the activity custom completion classes.
Here it is how the callbacks were replaced in multiple Moodle Core plugins: https://github.com/moodle/moodle/commit/334b6c75a43ea2a72995d14ee9526e6b82662270.

**Comment by NicoAlexH** [comment]
Removed deprecated call in https://github.com/ndunand/moodle-mod_choicegroup/commit/4f897a406507f992a605b86d0f14c3e61db029fe

Thank you @marcestone !
