### ISSUE TITLE
Invalid default activity completion settings

### ISSUE THREAD

**Issue by voegii** [ndunand/moodle-mod_choicegroup#212]
This Plugin produces a Javascript error on the default activity completion (/course/defaultcompletion.php?id=1) on Moodle 4.3+. The page does not work properly and invalid completion settings may be saved. 
E.g. the forum completion settings: As a result, no new forum activity can be added to the a course.

The Javascript error on the default activity completion is: "TypeError: Cannot read properties of null (reading 'get')" on line 233 on yui/form/form.js
![image](https://github.com/user-attachments/assets/32b6c2e9-db48-408c-8a79-ee529d907656)

As a workaround, we changed line 291 in mod_form.php:
```
        if (!str_ends_with($this->get_form()->getAttribute('action'), '/course/defaultcompletion.php')) {
            $this->js_call();
        }
```

**Comment by kskrige** [comment]
Thanks for this workaround. This error caused us a lot of problems.

**Comment by kskrige** [comment]
Is there a plan to fix this in a new version of the plugin?

**Comment by voegii** [comment]
I have just made a pull request that includes our workaround.

**Comment by kskrige** [comment]
Thanks very much @voegii

**Comment by kskrige** [comment]
Just in case others are experiencing this problem: This fix means that erroneous data will no longer be created by the plugin. However, if the problem data has already been triggered in the database, it will not be removed by the fix. We removed the problematic data by hand with a database query.

**Comment by ranver** [comment]
A workaround is to delete this:

"completiongradeitemnumber":"0"

from the custom rules cell.
