### ISSUE TITLE
Error reading from database because plugin is using type 'unsigned'

### ISSUE THREAD

**Issue by aneno-m-e** [ndunand/moodle-mod_choicegroup#229]
This issue has been introduced by PR #221. The 'unsigned' types are only available in MySQL, so the plugin breaks when using another database management system.

This commit will either need to be reverted or a solution working across all databases found rapidly As this breaks course pages. For the moment, we have reverted this change on our install.

**Comment by ndunand** [comment]
Thanks for the bug report. Reverting as 77f283992854c66d for the time being. Bump @Benjamin-unige fyi
