### ISSUE TITLE
REGEXP_SUBSTR not compatible with PostgreSQL

### ISSUE THREAD

**Issue by izendegi** [ndunand/moodle-mod_choicegroup#235]
We've detected that when adding a choicegroup activity with the latest version of the plugin we get an error:

```
ERROR:  function regexp_substr(character varying, unknown) does not exist
LINE 6:                  ORDER BY  CAST(REGEXP_SUBSTR(name, '[0-9]+'...
```

The source of the error is that the REGEXP_SUBSTR [used on lib.php](https://github.com/ndunand/moodle-mod_choicegroup/blob/master/lib.php#L854) is not compatible with PostgreSQL.

The equivalent for REGEXP_SUBSTR in PostgreSQL is _regexp_matches_, but I think none of them are standard SQL and compatible with all the DBMS, so I don't know which would be the best solution...

**Comment by NicoAlexH** [comment]
We ended up removing this part of the code ; it should not happen anymore https://github.com/ndunand/moodle-mod_choicegroup/commit/b6c7f1d96b14ae3038a329d977a3f1db96468ab7
