### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by relecand** [ndunand/moodle-mod_choicegroup#54]
Some improvements to German translations:
$string['choicegroupfull'] = 'Diese Gruppe ist voll, und es gibt keine verfügbaren Plätze mehr.';
$string['choicegroupname'] = 'Gruppenname';
$string['choicegroupoptions'] = 'Gruppen-Optionen';
$string['choicegroupsaved'] = 'Ihre Wahl wurde gespeichert';
$string['choicetext'] = 'Gruppenwahl-Text';
$string['modulename'] = 'Gruppenwahl';
$string['modulenameplural'] = 'Gruppenwahlen';
$string['modulename_help'] = 'Das Modul \'Gruppenwahl\' ermöglicht es Studenten, sich selbst in Gruppen innerhalb eines Kurses einzuteilen. Der Trainer wählt die Gruppen, die zur Abstimmung stehen sollen sowie das Maximum an Studenten, die in der jeweiligen Gruppen aufgenommen werden dürfen, aus.';
$string['pluginadministration'] = 'Gruppenwahl-Administration';
$string['pluginname'] = 'Gruppenwahl';
$string['publishafterclose'] = 'Ergebnisse nur zeigen, nachdem die Wahl beendet ist';
$string['responses'] = 'Wahlergebnisse';

**Comment by ndunand** [comment]
Hello,

I have no plans for a 2.8 version, but you are free to test it on 2.8 and tell me if there are any issues. Then I would fix them promptly and release an official 2.8 version.

**Comment by abias** [comment]
Hi Christian, hi Nicolas,

today, I noticed that the choicegroup plugin has been renamed for Moodle version 2.8 down to 2.1 in AMOS from "Gruppenabstimmung" to "Gruppenwahl" together with all plugin strings containing the term "abstimmung" or "wahl" at christmas by Ralf Krause, the german language pack maintainer.

I don't know why he made this change, but we don't need to think anymore when or if to rename the plugin as this was a language pack maintainer's decision.

Alex
