### ISSUE TITLE
Sort choicegroup options by name instead of by id

### ISSUE THREAD

**Issue by abias** [ndunand/moodle-mod_choicegroup#57]
Hi,

we have seen that the choicegroup options on /mod/choicegroup/view.php are sorted by id. This makes so sense to the average user as the groups are effectively sorted by creation date.

Please sort the groups in the options list by name just like it is done on the Moodle core gorups list (/group/index.php)

Thanks,
Alex

**Comment by abias** [comment]
Hi Nicolas,

I didn't hear from you about this topic for a month now. So I thought again what arguments are there not to change the sort order of the choicegroup options to alphabetical order. As the current sort order is only arbitrary in my point of view, I didn't find any arguments.

So I created a pull request in https://github.com/ndunand/moodle-mod_choicegroup/pull/59 for the small change to alphabetical order. If you want to have some possibility to let the teacher choose the sort order, please describe to me what you want to have and I will change the pull request.

Thanks,
Alex

**Comment by ndunand** [comment]
Hi Alex,

Thanks for PR #59, but I would like users to have an option -- here's why.

Many of our teachers use it for organizational purposes. For instance they organize special hands-on sessions which can only accommodate 20 students each, so they create groups "hands-on session Monday", "... Wednesday", "... Friday". The groups are created in that order (Mon, Wed, Fri) so they appear in the Group Choice in their "natural" order. But if they were to be sorted alphabetically, the resulting order would be "Friday, Monday, Wednesday", which would surely confuse some users. So here's why I really would like our teachers to have to option (opt-in) to sort the groups alphabetically in the Group Choice display.

So to wrap up, I would like:
1. the default behavior to be the same as now
2. per activity instance, an option to sort the choices (groups) alphabetically
3. if you need the default to be different, a new admin setting to set the default behavior

The reason for 1. and 3. is that I don't want any existing activities to change appearance without the user's (teacher's) explicit consent.

**Comment by abias** [comment]
Hi Nicolas,

thanks for the explanation.

I can create the activity instance setting and the admin setting for the default behaviour.
But before I do that, let me ask you one thing:

With your current behaviour for displaying the group list in mod_choicegroup, you are sorting by the mdl_choicegroup_options.id, not mod_groups.id. To me, it seems as it is not guaranteed by design that sorting by mdl_choicegroup_options.id really and always sorts by the group creation order like you described it. 
For example, I added a bunch of groups to the choicegroup activity, saved it, and then added another bunch of groups to the choicegroup activity - the result in the groups list was that they were sorted by the date added to the activity, not by creation date. 
Do you still think that this behaviour is intended and can be sold as "Sort by group creation date"?

Thanks,
Alex

**Comment by ndunand** [comment]
Hi Alex,

You are right indeed, thanks for pointing this out. I mixed things a little bit here, because the way the user adds groups (choices) to the activity has changed from the beginning. One used to be able to select within the activity settings the order in which the groups were displayed, therefore it made sense to display the groups sorted by `mdl_choicegroup_options.id`. Now that the activity settings UI has changed a lot (can't set an order explicitly anymore), this does not make sense anymore.

So, the behavior would be to have the two options I described in my last post. Commit 31789ac takes care of sorting the choices by group creation date now.

Thanks,
Nicolas

**Comment by abias** [comment]
Hi Nicolas, 

one more question before we implement the changes:
You said that the default behavior should be the same as now. I think, globally, it would make more sense to have the new default to be "sort alphabetically", especially for new installations of the plugin.

Would you agree that we:
- create a new admin setting to set the default behavior which defaults to "sort alphabetically"? Users who definitely want to sort by ID will be able to set their default for future instances of the plugin.
- add an update script to the plugin which makes sure that all existing instances of the plugin are set to sort by id so that the behaviour of existing instances won't change?

Thanks,
Alex

**Comment by ndunand** [comment]
Hi Alex,

Yes, I agree completely. Thanks for stating this – it makes sense not to change existing plugin instances indeed.

**Comment by andrewhancox** [comment]
Nicolas/Alex
I've created a new pull request at https://github.com/ndunand/moodle-mod_choicegroup/pull/64 which contains the proposed solution. I've opted not to use an update script but defaulting to ensure that existing instances are not effected.

**Comment by ndunand** [comment]
Hi Andrew, thanks a lot!

Alex, would you mind trying this? If you're happy with the way it works I'll merge Andrew's PR.

**Comment by abias** [comment]
Hi Nicolas, hi Andrew,

I just tried the version from the pull request, it does what it is expected to do :)

Two small things:
@andrewhancox The "Sort groups by" widget in the activity settings gives three options: System default, ID, Name. User's won't know what the system default is and will probably choose a fixed setting although this would not be necessary. Could you please change your PR that the widget says "System default (ID)" respectively "System default (Name)"?
@ndunand You might want to add some information about the new settings page to your Readme file.

Thanks,
Alex

**Comment by ndunand** [comment]
Right, I agree with Alex about the labelling. Moreover, most users probably don't know what ID is either. Maybe replace "ID" with "group creation date" ?

**Comment by andrewhancox** [comment]
Nicolas,
I considered doing that but help back since that’s not what is actually happening and I would worry that there will be some strange edge case that means sorting by ID is not the same as sorting by creation date. We could actually sort by creation date?

**Comment by ndunand** [comment]
Andrew, I might be missing sth, but as far as I understand things sorting by `groups.id` is the same as sorting by group creation date (after all, the `groups` table has an auto-incremented `id` field).

**Comment by andrewhancox** [comment]
I'm just concerned that there could be some situation where sorting by the group id and sorting by created date does not have the same effect - I'm thinking of scenarios like db restores, people manually changing data etc - it's definitely an edge case and one you could ignore but I think it would be cleaner to actually order by creation date if that is what we will say we're sorting by. It's a very quick change if you're happy with it.

**Comment by ndunand** [comment]
You are right, such cases are not totally implausible. So I'd be very happy if you could do this change, and I'll then happily merge your PR.

**Comment by andrewhancox** [comment]
I've made the change and it seems to be in the pull request.

**Comment by ndunand** [comment]
Great! Thanks again for your code.

**Comment by abias** [comment]
Thanks, Andrew, for the code!

Nicolas, could you please add the updated plugin to the Moodle plugin repo? Then we can translate the new strings in AMOS. Thanks :)

**Comment by abias** [comment]
Hi Andrew,

you may have overseen my comment saying 
> The "Sort groups by" widget in the activity settings gives three options: System default, ID, Name. User's won't know what the system default is and will probably choose a fixed setting although this would not be necessary. Could you please change your PR that the widget says "System default (ID)" respectively "System default (Name)"?
At least I don't find this change in the (now merged) pull request.

Could you please have a look at this, if you agree?

Thanks,
Alex

**Comment by ndunand** [comment]
Well, I've already merged the PR anyway, so you could always make a new mini PR to change only these language strings.
