### ISSUE TITLE
Add e-mail column to text format export function

### ISSUE THREAD

**Issue by abias** [ndunand/moodle-mod_choicegroup#58]
Hi Nicolas,

I saw that you implemented the e-mail export function in https://github.com/ndunand/moodle-mod_choicegroup/issues/46, but in my point of view it's only implemented for the excel and ods format, but it is missing for the text format export. Might this be true? Could you please implement it for text format, too, to achieve consistency?

Thanks,
Alex

**Comment by ndunand** [comment]
Hi Alex,

Thanks for pointing this out. This has been resolved in commit e8cfecafae66d0269c1d4175f804fa45a8230da9 .

Best regards,
Nicolas

**Comment by abias** [comment]
Great, thanks!

Could you please upload the new version to the Moodle plugins repository so that we can use standard update mechanisms?

Thanks,
Alex

**Comment by ndunand** [comment]
Hi Alex,
Yes, I'm just waiting for the test results of this module on Moodle 2.8 to release a new version, which will include this and also officially support Moodle 2.8.

**Comment by ndunand** [comment]
There, Alex: the new version has been released.

**Comment by abias** [comment]
Thanks, Nicolas, this is good news!

Alex
