### ISSUE TITLE
Fatal error: Call to undefined method cm_info::create() : this function only exists in Moodle 2.8 !

### ISSUE THREAD

**Issue by comete-upo** [ndunand/moodle-mod_choicegroup#63]
Hi,

We installed the lastest version and now we got this error when we try to access to choicegroup activity :
Fatal error: Call to undefined method cm_info::create() in /moodle/mod/choicegroup/lib.php on line 832

We are running Moodle 2.7.5 and we found that the create() function does not exist in Moodle 2.7 ! 
The function only exists in moodle 2.8.

You can check this here : 
> http://fossies.org/dox/moodle-2.8.3/classcm__info.html
"Static Public Member Functions
static 	create ($cm, $userid=0)"

> http://fossies.org/dox/moodle-2.7.5/classcm__info.html
no create() function

Can you fix it ? (maybe by creating branchs for each version ?)

**Comment by steveorulez** [comment]
we just reverted to the old code on line 832 waiting for a patch

**Comment by comete-upo** [comment]
Thanks but I can found the new code ?

We did it manually but we got this error now : 

Erreur de programmation détectée. Ceci doit être corrigé par un programmeur : PHP catchable fatal error

Plus d'informations sur cette erreur
Debug info: Argument 1 passed to core_availability\info_module::__construct() must be an instance of cm_info, instance of stdClass given, called in [dirroot]/mod/choicegroup/lib.php on line 832 and defined
Error code: codingerror
Stack trace:
    line 393 of /lib/setuplib.php: coding_exception thrown
    line 45 of /availability/classes/info_module.php: call to default_error_handler()
    line 832 of /mod/choicegroup/lib.php: call to core_availability\info_module->__construct()
    line 167 of /mod/choicegroup/view.php: call to choicegroup_get_response_data()

I would like to reuse the old version , can I use this version without to change something in the database ? (did you change anything in the DB between this version and the last ?)

**Comment by steveorulez** [comment]
i just copied the code in the function create (moodle2.8) to create the $cminfo there should be no problem

$modinfo = get_fast_modinfo($cm->course);
$cminfo = $modinfo->get_cm($cm->id);  
$availability = new \core_availability\info_module($cminfo);
$users = $availability->filter_user_list($users);

**Comment by comete-upo** [comment]
ok, thanks !

**Comment by ndunand** [comment]
Thanks @steveorulez I'll go your way, as I don't really want to maintain different branches for 2 differing lines of code.
