### ISSUE TITLE
Order groups alphabetically

### ISSUE THREAD

**Issue by Cheesenbizkitz** [ndunand/moodle-mod_choicegroup#68]
Hi, 

I've got a client who is using this plugin to allow people to choose from a list of locations to select where they want to attend the course. They can choose from locations all over the world at places where the course is run.

The problem is, as they add more locations to the selectable list, the order they are shown to the student is the order in which the group was added. Because they have a lot of people with english as a second language and because a large chunk of groups at the top are in alphabetical order, these students don't think to scroll down and sift through all of the out of order groups to find their location.

Is there a way to get the groups to order alphabetically for the student easily? I'm going to dig into the PHP right now, but I haven't had much luck ordering things in Moodle in the past, so help would be very much appreciated.

Thanks.

**Comment by ndunand** [comment]
Hi, the version released a few days ago features just exactly that. (see #57)

**Comment by Cheesenbizkitz** [comment]
Ah, sorry, I didn't think to check there.

Thanks!

**Comment by ndunand** [comment]
Alright, good 😊

**Comment by abias** [comment]
It's nice to see that there are other users who appreciate our sort-by-name contribution to this plugin :)
