### ISSUE TITLE
Can't edit option when group is full

### ISSUE THREAD

**Issue by jguille2** [ndunand/moodle-mod_choicegroup#70]
Hi,
-When a group option is full (number_members=max_capacity) the checkbox option is disabled.
-I'ts ok when option is not selected... because choosing it is not allowed.
-But when option is selected (is the user option) if editing is allowed, checkbox must not be disabled, because user must be able to disable it.

Thanks
Joan

**Comment by ndunand** [comment]
Hi,
Thanks for sharing your thoughts. Indeed that would make more sense. I'll look into this when updating the plugin to officially support Moodle 2.9.

**Comment by ndunand** [comment]
Fixed in #72
