### ISSUE TITLE
Proposal to change one string

### ISSUE THREAD

**Issue by jguille2** [ndunand/moodle-mod_choicegroup#71]
Hi,
We have 'Fill' and 'Fill/Capacity' in headers, tot introduce the number of members of the groups.
I think 'fill' is not the right word.
I propose to use 'Members' and 'Members/Capacity' instead.

Thanks,
Joan

**Comment by ndunand** [comment]
Hi,
Right, again. I'll change this in the upcoming release.

**Comment by ndunand** [comment]
Fixed in #73
