### ISSUE TITLE
Activity with no selected groups throws notice

### ISSUE THREAD

**Issue by thepurpleblob** [ndunand/moodle-mod_choicegroup#80]
This is possible when choicegroup is upgraded from earlier versions. 

Notice: Undefined property: stdClass::$option in /var/www/moodle29/mod/choicegroup/lib.php on line 306

Warning: Invalid argument supplied for foreach() in /var/www/moodle29/mod/choicegroup/lib.php on line 306

You can achieve the same thing by deleting all the groups from the course administration menu as well. A proper check is needed for no groups.

**Comment by kristian-94** [comment]
I have submitted a PR for this

**Comment by ndunand** [comment]
Thanks for reporting and for the PR. Closing now
