### ISSUE TITLE
Hardcoded "lang=en" in a link

### ISSUE THREAD

**Issue by magaudreau** [ndunand/moodle-mod_choicegroup#81]
There is a hardcoded "lang=en" in mod_form.php.

I used "current_language()" to replace the "en" and it seems to do the right thing.

**Comment by ndunand** [comment]
Well spotted, thanks! I'll fix this in the next release.

**Comment by magaudreau** [comment]
While you're at it, there is also a hardcoded "Help with Choice options" on the same line.

**Comment by michael-milette** [comment]
Just a gentle reminder that neither of these two issues have been addressed in the latest version of your code on GitHub.

**Comment by ndunand** [comment]
Thanks, fixed in 21d3ce3c9
