### ISSUE TITLE
performance issues ?

### ISSUE THREAD

**Issue by ndunand** [ndunand/moodle-mod_choicegroup#89]
Possible performance issues, as reported by Sara Cenni on [the Moodle.org plugin page](https://moodle.org/plugins/mod_choicegroup).

A quick test with 2000 students revealed no big performance issues, below is the profiling callgraph for the `mod/choicegroup/report.php` page (displaying users with no response), seeming to indicate the bottleneck to be calculating all users' names for display.

![mod_choicegroup-report php_callgraph](https://cloud.githubusercontent.com/assets/762972/13110236/fbd7bdb0-d57e-11e5-9306-b5b065114695.png)

**Comment by s-cenni** [comment]
Hi Nicolas,
This is my profiling callgraph for `mod/choicegroup/view.php` with a course with 3647 users.

![3647](https://cloud.githubusercontent.com/assets/4058151/13249212/428ef964-da23-11e5-9dc3-ced8d3928dca.png)


Below the report with 1547 users

![1547](https://cloud.githubusercontent.com/assets/4058151/13249283/b325cfc2-da23-11e5-8d61-5a2fd73b8524.png)

**Comment by ndunand** [comment]
Thanks for the callgraphs. Yes indeed, the `choicegroup_get_user_answer` (called once per enrolled user) seems to be the bottleneck here, as you supposed initially.

**Comment by ndunand** [comment]
What about trying to implement the code modification you were talking about? Is this something you could do? If it proves a real improvement and passes all tests, I'd be glad to include it.

**Comment by s-cenni** [comment]
I thought about your proposal, but unfortunately in these weeks I'm too busy to study the plugin code and to implement the code modification. :(  In the near future I hope I have enough time to implement it because we really appreciate your plugin and we found it very useful!!
Thank you!
Sara

**Comment by ndunand** [comment]
Alright, thanks for posting back. I'm leaving this open so that we can report back here later on.

**Comment by bonimat** [comment]
I'm Sara's collegue . We spoke about the problem few weeks ago, and we have worked on a potential solution.
Do you prefer receive my code by email or do I have to post it in this forum?

**Comment by ndunand** [comment]
Hi. Thanks, the best for me would be that you initiate a pull request, so I could easily review the changes. See the documentation here: https://help.github.com/articles/using-pull-requests/

**Comment by ndunand** [comment]
Addresses by https://github.com/ndunand/moodle-mod_choicegroup/pull/90
