### ISSUE TITLE
Moodle 3.1 compatibility

### ISSUE THREAD

**Issue by bgoodlin01** [ndunand/moodle-mod_choicegroup#92]
I notice that this project is listed as compatible with Moodle 3.0 but not 3.1.  Is there anything preventing this from being 3.1-compatible?  My Moodle tech is hesitant about installing anything on our 3.1 server if it isn't explicitly listed as being compatible with 3.1.  Thanks!

**Comment by ndunand** [comment]
Thanks for the reminder, releasing now official Moodle 3.1 support.
